// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaOsSxxW232KVl8vBbYqo-8BdIdYuY9zA',
    appId: '1:168139640366:web:f365c427a2fb5e171099bf',
    messagingSenderId: '168139640366',
    projectId: 'fir-extensions-example',
    authDomain: 'fir-extensions-example.firebaseapp.com',
    storageBucket: 'fir-extensions-example.appspot.com',
    measurementId: 'G-06XSK3QR5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLeS1Jb_8kB8rwbi6jzpXrMRj6i_7GYfI',
    appId: '1:168139640366:android:6ddac78c194316c21099bf',
    messagingSenderId: '168139640366',
    projectId: 'fir-extensions-example',
    storageBucket: 'fir-extensions-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWdxLIwRm8NGxDkhaLZ_31F2gnp7oPK_4',
    appId: '1:168139640366:ios:123138a3239a163a1099bf',
    messagingSenderId: '168139640366',
    projectId: 'fir-extensions-example',
    storageBucket: 'fir-extensions-example.appspot.com',
    iosBundleId: 'com.example.firExtensionsDemo',
  );
}
